'use client'
import { useActionState, useState } from 'react'
import type { InferSelectModel } from 'drizzle-orm'
import { saveArtworkAction, type ActionState } from '@/app/admin/actions'
import type { artworks } from '@/db/schema'
import { slugify } from '@/lib/slug'

type Artwork = InferSelectModel<typeof artworks>
const blank = { title: '', slug: '', year: new Date().getFullYear(), medium: '', type: 'image', status: 'draft', description: '', mediaPath: '', externalUrl: '', sourceUrl: '', componentKey: '', altText: '', dimensions: '', duration: '', edition: '', fileSize: '', dateCreated: '', software: '', hardware: '', programmingLanguage: '', autoplay: true, muted: true, loop: true, controls: true } as const
export function ArtworkForm({ artwork, componentKeys }: { artwork?: Artwork; componentKeys: string[] }) {
  const data = artwork ?? blank; const [type, setType] = useState(data.type); const [title, setTitle] = useState(data.title); const [slug, setSlug] = useState(data.slug); const [slugTouched, setSlugTouched] = useState(Boolean(artwork))
  const bound = saveArtworkAction.bind(null, artwork?.id ?? null)
  const [state, action, pending] = useActionState(bound, {} as ActionState)
  const field = (name: keyof typeof data, label: string, typeName = 'text') => <div><label className="admin-label" htmlFor={name}>{label}</label><input className="admin-input" id={name} name={name} type={typeName} defaultValue={String(data[name] ?? '')} /></div>
  return <form action={action} encType="multipart/form-data" className="mt-10 space-y-8">
    <div className="admin-grid"><div><label className="admin-label" htmlFor="title">Title</label><input className="admin-input" id="title" name="title" value={title} required onChange={(e) => { setTitle(e.target.value); if (!slugTouched) setSlug(slugify(e.target.value)) }} /></div><div><label className="admin-label" htmlFor="slug">Slug</label><input className="admin-input" id="slug" name="slug" value={slug} required onChange={(e) => { setSlugTouched(true); setSlug(slugify(e.target.value)) }} /></div>{field('year','Year','number')}{field('medium','Medium')}</div>
    <div className="admin-grid"><div><label className="admin-label" htmlFor="type">Artwork type</label><select className="admin-input" id="type" name="type" value={type} onChange={(e) => setType(e.target.value as typeof type)}><option value="image">Image</option><option value="video">Video</option><option value="interactive">Interactive</option><option value="external">External</option></select></div><div><label className="admin-label" htmlFor="status">Status</label><select className="admin-input" id="status" name="status" defaultValue={data.status}><option value="draft">Draft</option><option value="published">Published</option></select></div></div>
    <div><label className="admin-label" htmlFor="description">Short description</label><textarea className="admin-input" id="description" name="description" defaultValue={data.description ?? ''} /></div>
    {type === 'interactive' && <fieldset className="border-t border-[var(--divider)] pt-6"><legend className="mb-5 text-xl">Interactive artwork</legend><div className="admin-grid"><div><label className="admin-label" htmlFor="externalUrl">External iframe URL</label><input className="admin-input" id="externalUrl" name="externalUrl" defaultValue={data.externalUrl ?? ''} /></div><div><label className="admin-label" htmlFor="componentKey">Or registered component</label><select className="admin-input" id="componentKey" name="componentKey" defaultValue={data.componentKey ?? ''}><option value="">None</option>{componentKeys.map((key) => <option key={key}>{key}</option>)}</select></div></div><p className="mt-3 text-xs text-black/55">External URLs are sandboxed. Database content is never evaluated as code.</p></fieldset>}
    {type === 'external' && <div><label className="admin-label" htmlFor="externalUrl">External artwork URL</label><input className="admin-input" id="externalUrl" name="externalUrl" type="url" defaultValue={data.externalUrl ?? ''} /></div>}
    {type !== 'interactive' && type !== 'external' && <input type="hidden" name="externalUrl" value="" />}{type !== 'interactive' && <input type="hidden" name="componentKey" value="" />}
    <fieldset className="border-t border-[var(--divider)] pt-6"><legend className="mb-5 text-xl">Technical information</legend><div className="admin-grid">{field('dimensions','Dimensions')}{field('duration','Duration')}{field('edition','Edition')}{field('fileSize','File size')}{field('dateCreated','Date created','date')}{field('software','Software')}{field('hardware','Hardware')}{field('programmingLanguage','Programming language')}{field('sourceUrl','Source URL','url')}</div></fieldset>
    {(type === 'image' || type === 'video') && <fieldset className="border-t border-[var(--divider)] pt-6"><legend className="text-xl">Primary Media</legend><p className="mb-5 mt-3 max-w-2xl text-sm leading-relaxed text-black/55">This is the first media displayed at the top of the public artwork page. You can add more images, videos, or iframe artworks in Additional Media below.</p><div><label className="admin-label" htmlFor="media">Upload {type}</label><input className="admin-input pt-3" id="media" name="media" type="file" accept={type === 'video' ? 'video/mp4,video/webm' : 'image/jpeg,image/png,image/webp,image/gif,image/avif'} /></div><div className="mt-4"><label className="admin-label" htmlFor="mediaUrl">Or media URL</label><input className="admin-input" id="mediaUrl" name="mediaUrl" defaultValue={data.mediaPath ?? ''} /></div>{type === 'image' && <div className="mt-4">{field('altText','Alternative text')}</div>}{type === 'video' && <div className="mt-5 flex flex-wrap gap-6 text-sm">{(['autoplay','muted','loop','controls'] as const).map((key) => <label key={key} className="flex items-center gap-2 capitalize"><input type="checkbox" name={key} defaultChecked={Boolean(data[key])} />{key}</label>)}</div>}</fieldset>}
    {state.error && <p role="alert" className="text-sm text-red-800">{state.error}</p>}<button className="admin-button" disabled={pending}>{pending ? 'Saving…' : data.status === 'published' ? 'Save artwork' : 'Save artwork'}</button>
  </form>
}
